language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - ROS_REPO=main
  matrix:
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="kinetic" ROS_REPO=ros-testing
    - ROS_DISTRO="kinetic" PRERELEASE=true
    - ROS_DISTRO="melodic"
    - ROS_DISTRO="melodic" ROS_REPO=ros-testing
    - ROS_DISTRO="melodic" PRERELEASE=true

install:
  - git clone --quiet --depth=1 -b master https://github.com/ros-industrial/industrial_ci.git .industrial_ci

script:
  - .industrial_ci/travis.sh
